{% set name = "aioxmpp" %}
{% set version = "0.13.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aioxmpp-{{ version }}.tar.gz
  sha256: a2299e84f6d61137c6a046e2470aeebd8cd25515c1f3cefd681c322242d8056d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - aiosasl >=0.3
    - aioopenssl >=0.1
    - babel >=2.3,<3.dev0
    - dnspython >=1.0,<3.0
    - lxml >=4.0,<5.dev0
    - multidict <7,>=2.0
    - sortedcollections >=2.1,<3.dev0
    - pyopenssl
    - pyasn1
    - pyasn1-modules
    - tzlocal >=1.2

test:
  imports:
    - aioxmpp
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/horazont/aioxmpp
  summary: Pure-python XMPP library for asyncio
  license: LGPL-3.0-only AND LGPLLR AND GPL-3.0-only
  license_file:
    - COPYING.LESSER
    - COPYING.gpl3
    - LICENSES

extra:
  recipe-maintainers:
    - akrherz
